name: holaride_app
description: HolaRide — intercity ride-sharing for Cameroon.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  http: ^1.2.0
  shared_preferences: ^2.2.0
  cupertino_icons: ^1.0.6
  image_picker: ^1.1.2
  url_launcher: ^6.3.0
  geolocator: ^11.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  supabase_flutter: ^2.8.0
  google_maps_flutter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/splash_bg.jpg
    - assets/images/hero_car.png
    - assets/images/empty_trips_bg.png
    - assets/images/ride_share_car.png
    - assets/images/onboard_1.png
    - assets/images/onboard_2.png
    - assets/images/hero_banner.png
    - assets/images/find_ride_car.png
    - assets/images/offer_ride_car.png
    - assets/images/ride_together.png
    - assets/images/learn_more.png
    - assets/images/welcome_bg.png
    - assets/images/hero_road.png
    - assets/images/orange_money.png
    - assets/images/mtn_money.png