import 'package:flutter/material.dart';
import '../../theme/app_colors.dart';

/// Placeholder only. I'm not drafting real Terms of Service or a
/// Privacy Policy here — those are legal documents that should come
/// from you (or a lawyer), not be generated by an AI assistant and
/// shipped as if they were reviewed. This screen exists so the
/// "Terms and Privacy Policy" link on phone entry and this Profile
/// menu item both go somewhere real instead of a dead end, with an
/// honest note about what's actually here.
class TermsPrivacyScreen extends StatelessWidget {
  const TermsPrivacyScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.surface,
      appBar: AppBar(title: const Text('Terms & Privacy Policy')),
      body: Padding(
        padding: const EdgeInsets.all(20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Container(
              padding: const EdgeInsets.all(16),
              decoration: BoxDecoration(
                color: AppColors.warningBg,
                borderRadius: BorderRadius.circular(14),
              ),
              child: const Text(
                'This screen is a placeholder. Real Terms of Service and a Privacy '
                'Policy — ideally reviewed by a lawyer familiar with Cameroonian '
                'consumer and data protection law, given this app handles real '
                'payments and personal data — need to replace this text before '
                'launch.',
                style: TextStyle(color: AppColors.warning, fontSize: 13, height: 1.5),
              ),
            ),
            const SizedBox(height: 18),
            const Text(
              'At minimum, your real policy should cover things like: what data '
              'HolaRide collects (phone number, location, payment details), how '
              'Mobile Money transactions are handled, the cancellation fee '
              'structure, driver vetting and liability, and how a person can '
              'request their data be deleted.',
              style: TextStyle(color: AppColors.textSecondary, height: 1.5, fontSize: 13.5),
            ),
          ],
        ),
      ),
    );
  }
}
